### ISSUE TITLE
Add unit test scenarios for UnsavedRelationList

### ISSUE THREAD

**Issue by chrispenny** [silverstripe-terraformers/keys-for-cache#59]
Not entirely sure what triggers an `UnsavedRelationList` to exist. Will need to look into that. First guess is that it might be when an unsaved model is added to a `DataList`?
```php
$model = NewModel::create();
// $model hasn't been saved yet
$page->Models()->add($model);
```

**Comment by GuySartorelli** [comment]
I _think_ it's the other side of the relation not being written yet which triggers this
```php
$page = Page::create();
$page->Models()->add(SomeModel::get()->first()); // I think $page->Models() is an `UnsavedRelationList`
```
